---
- name: install restart apache2
  hosts: localhost
  become: yes 
  tasks:
  - name: install apache2
    apt: 
      name: apache2
      state: present

  - name: restart with systemd
    systemd:
      name: apache2
      state: restarted
