--- # exmapleo fo loop in the ansible 
- name: loop example
  hosts: myproduction 
  become: yes 

  vars:

  tasks: 
  - yum: 
      name: "{{ item }}"
      state: absent
    with_items:
#    loop: 
      - elinks
      - nginx
      - bind-utils
